steps:
  # Build backend image
- name: 'gcr.io/cloud-builders/docker'
  id: 'build-backend'
  args:
    - 'build'
    - '-t'
    - 'gcr.io/$PROJECT_ID/documentation-assistant-backend:$SHORT_SHA'
    - '-f'
    - 'backend/Dockerfile'
    - 'backend'

# Push backend image
- name: 'gcr.io/cloud-builders/docker'
  id: 'push-backend'
  args:
    - 'push'
    - 'gcr.io/$PROJECT_ID/documentation-assistant-backend:$SHORT_SHA'

# Deploy backend to Cloud Run
- name: 'gcr.io/google-appengine/cloud-builders/gcloud'
  id: 'deploy-backend'
  args:
    - 'run'
    - 'deploy'
    - 'documentation-assistant-backend'
    - '--image'
    - 'gcr.io/$PROJECT_ID/documentation-assistant-backend:$SHORT_SHA'
    - '--region'
    - 'us-central1'  # Change to your region
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--set-env-vars'
    - "LOG_LEVEL=DEBUG"
    - '--set-env-vars'
    - "GCS_BUCKET_NAME=${_GCS_BUCKET_NAME}"
    - '--set-env-vars'
    - "PROJECT_ID=${_PROJECT_ID}"


# Build frontend image
- name: 'gcr.io/cloud-builders/docker'
  id: 'build-frontend'
  args:
    - 'build'
    - '-t'
    - 'gcr.io/$PROJECT_ID/documentation-assistant-frontend:$SHORT_SHA'
    - '-f'
    - 'frontend/Dockerfile'
    - 'frontend'

# Push frontend image
- name: 'gcr.io/cloud-builders/docker'
  id: 'push-frontend'
  args:
    - 'push'
    - 'gcr.io/$PROJECT_ID/documentation-assistant-frontend:$SHORT_SHA'

# Deploy frontend to Cloud Run
- name: 'gcr.io/google-appengine/cloud-builders/gcloud'
  id: 'deploy-frontend'
  args:
    - 'run'
    - 'deploy'
    - 'documentation-assistant-frontend'
    - '--image'
    - 'gcr.io/$PROJECT_ID/documentation-assistant-frontend:$SHORT_SHA'
    - '--region'
    - 'us-central1'  # Change to your region
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--set-env-vars'
    - "BACKEND_URL=https://documentation-assistant-backend-xxxxxxxxxxx-ew.a.run.app" # Replace with your backend Cloud Run url
    - '--set-env-vars'
    - "LOG_LEVEL=DEBUG"
substitutions:
   _OPENAI_API_KEY: "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"
   _GCS_BUCKET_NAME: "documentation-assistant"
   _PROJECT_ID: "gpt-projects-scalable"